version: "3.8"
services:
  mqtt:
    build: ./mqtt
    ports:
      - 3001:3001
    links:
      - api
    restart: always
  api:
    build: ./api
    ports:
      - 3000:3000
    links:
      - mongo
    restart: always
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    restart: always

volumes:
  mongo-data:
