version: "3.8"
services:
  mqtt:
    build: ./mqtt
    ports:
      - 3001:3001
    links:
      - api
    restart: always

  api:
    build: ./api
    ports:
      - 3000:3000
    links:
      - mongo
    restart: always

  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    restart: always
  
  producer:
    build: 
      context: ./worker-service/producers
      dockerfile: Dockerfile
    environment:
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_HOST=redis
    ports:
      - "3002:3002"
    links:
      - api

  consumer:
    build: 
      context: ./worker-service/consumers
      dockerfile: Dockerfile
    environment:
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_HOST=redis

  redis:
    image: redis
    container_name: redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"

volumes:
  mongo-data:

networks:
  worker:
    driver: bridge
